name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install ruff mypy transformers
      - name: py_compile
        run: python -m py_compile $(git ls-files '*.py')
      - name: ruff
        run: ruff check wan_ps1_engine.py
      - name: mypy
        run: mypy --ignore-missing-imports wan_ps1_engine.py
      - name: wan_ps1_engine help
        run: python wan_ps1_engine.py --help > /dev/null
      - name: wan_ps1_engine dry run
        run: python wan_ps1_engine.py --dry-run
