name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install ruff mypy pytest
      - name: Ruff
        run: ruff check .
      - name: Mypy
        run: mypy --ignore-missing-imports wan_ps1_engine.py
      - name: py_compile
        run: python -m py_compile $(git ls-files '*.py')
      - name: Help
        run: python wan_ps1_engine.py --help
      - name: Dry run
        run: python wan_ps1_engine.py --dry-run --attn auto --mode t2v --frames 8 --width 512 --height 288 --model_dir models/WAN
      - name: Pytest
        run: pytest -q
