name: wan-ci
on: [pull_request, push]

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install ruff mypy pytest
      - run: ruff check .
      - run: mypy --ignore-missing-imports wan_ps1_engine.py core
      - run: python -m compileall -q .
      - run: python wan_ps1_engine.py --help
      - run: python wan_ps1_engine.py --dry-run --mode t2v --prompt ok --frames 4 --fps 24 --width 1280 --height 704 --outdir out
      - run: pytest -q
